---
- hosts: ws
  become: true
  ignore_errors: true
  gather_facts: true
  become_user: root
  tasks:
    - name: Install apache
      shell: yum install httpd -y
      tags:
      - install
    - name: start apache service
      systemd:
        name: httpd
        state: started
        enabled: true
    - name: Create index.html file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Write content to index.html
      copy:
        dest: /var/www/html/index.html
        content: | # > everything in one line and | same format
          <html>
          <body>
          <h1>Welcome to Ansible Web Server</h1>
          <p>This is a simple web page served by Apache.</p>
          <p>Managed by Ansible playbook.</p>
          <p>Current date and time: {{ ansible_date_time.iso8601 }}</p
          <p>Server uptime: {{ ansible_uptime_seconds }} seconds</p>
          </body>
          </html>
      tags:
        - copy